<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38947515-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<div id="footer">
  
	<p class="legal">
		
		&nbsp;&nbsp;&nbsp;&nbsp;
              
                <a href="http://www.facebook.com/pages/Satrafficupdates/463800653691299" target="_blank"><img src="http://localhost/ci_traffic/images/ficon.jpg" alt="Follow us" /> </a> <a href="https://twitter.com/satrafficupdate" target="_blank"><img src="http://localhost/ci_traffic/images/ticon.png" alt="Follow us"/></a>
		Developed by <a href="http://masande.comuv.com" target="_blank">Masande</a></p>
</div>
<!-- end footer -->
</body>
</html>
